language: ruby
before_install: gem install bundler -v 1.11.2
script:
  - bundle exec rake spec
rvm:
  - 2.2
  - jruby
  - ruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
notifications:
  email:
    - antonkuzmenko.dev@gmail.com